# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME World
ENV LINODE_TOKEN "token"
ENV SERVER_PORT 8080
ENV NODEBALANCER_ID 123456
ENV FIREWALL_ID 789012
ENV ALLOWLIST_INTERVAL_MINUTES 10


# Run app.py when the container launches
CMD ["python", "app.py"]